apiVersion: v1
kind: Service
metadata:
  name: of-google-analytics
  namespace: openfaas
  labels:
    app: of-google-analytics
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: of-google-analytics
